### ISSUE TITLE
May process SASL negotiation BEFORE STARTTLS negotiation

### ISSUE THREAD

**Issue by coinicon72** [vukoye/xmpp_dart#1]
STARTTLS negotiation MUST be completed before proceeding to SASL negotiation, per [Extensible Messaging and Presence Protocol (XMPP): Core](https://xmpp.org/rfcs/rfc6120.html) 5.3.4.

If features returns from server as following:
```xml
<stream:features>
    <auth xmlns="http://jabber.org/features/iq-auth"/>
    <register xmlns="http://jabber.org/features/iq-register"/>
    <mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
        <mechanism>SCRAM-SHA-1</mechanism>
        <mechanism>PLAIN</mechanism>
        <mechanism>ANONYMOUS</mechanism>
    </mechanisms>
    <ver xmlns="urn:xmpp:features:rosterver"/>
    <starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/>
    <compression xmlns="http://jabber.org/features/compress">
        <method>zlib</method>
    </compression>
</stream:features>
```
xmpp_dart will process `auth` negotiation first, then `starttls` negotiation.

**Comment by vukoye** [comment]
You are right, thanks, I will fix it as soon as possible.

**Comment by vukoye** [comment]
Should be fixed (sorry for big delay)

**Comment by ol88** [comment]
Not sure if this helps but I still had the issue happening to me when calling:
`connection.open();`

I think the issue lies in the features waiting to be negotiated is not empty so when StartTLS negotiation starts asynchronously, the negotiator state is immediately set to `NegotiatorState.DONE` before the negotiation is actually finished. That would be a problem if the `waitingNegotators` queue was empty but it is not, the SASL negotiation is already waiting in the queue and starts processing before the secure socket is created.

The best way I found to simply avoid any issue is to clear the `waitingNegotators` before setting the state to `NegotiatorState.DONE`. This way, the secure socket starts with a fresh queue and no conflict.

In StartTlsNegotatior.dart add `_connection.streamFeaturesManager.waitingNegotators.clear();`

```
  void checkNonzas(Nonza nonza) {
    if (nonza.name == "proceed") {
      _connection.streamFeaturesManager.waitingNegotators.clear();
      state = NegotiatorState.DONE;
      subscription.cancel();
      _connection.startSecureSocket();
    } else if (nonza.name == "failure") {
      _connection.startTlsFailed();
    }
  }
```

I'm no expert in either XMPP or dart so not sure if it's the most elegant way to do this but seems to be working for me now.
